### ISSUE TITLE
import

### ISSUE THREAD

**Issue by r-bakker** [WorksOfLiam/Notepad-RPG#3]
Hi Barry,
I'm on Notepad++ 32 bits version 7.4.1. I tried to import sqlrpgle.xml, but it says 'fail to import'. Am I doing something wrong? And what do I do with functionList.xml?

**Comment by jjcllhn** [comment]
This is what worked for me:

- Hit the green Clone or Download button,
- select Download ZIP,
- extract the zip file into a local directory,
- import the sqlrpgle.xml file from that directory into Notepad++

Apparently right click Save As on the sqlrpgle.xml link just gives you the HTML for the page.

**Comment by WorksOfLiam** [comment]
Hi @r-bakker - does the issue persist?

**Comment by r-bakker** [comment]
No, it was a misunderstanding. I right clicked and saved the xml. It became an xml file, but the content became just plain html. So I think I saved the target html file as an xml. I repaired this by going to the html page and saved the code in a real xml file. Strange, I always worked this way and never had this problem. So I think the page is set up wrongly, in the first (wrong) way it should save as an html page, so you know this is not the way.

 

	
Met vriendelijke groeten,

	
Ruud Bakker

	

*

 <tel:+31104755237> 010-4755237


*

 <tel:0648783932> 06-48783932


"

 <http://ruud.bakker.oyoweb.nl/> http://ruud.bakker.oyoweb.nl


*

http://code.oyoweb.nl/


* 

 <mailto:ruud.bakker@oyoweb.nl> ruud.bakker@oyoweb.nl


in

 <http://www.linkedin.com/in/ruudbakker1> http://www.linkedin.com/in/ruudbakker1

 

 

Van: Liam Allan [mailto:notifications@github.com] 
Verzonden: woensdag 14 juni 2017 12:57
Aan: WorksOfLiam/Notepad-RPG <Notepad-RPG@noreply.github.com>
CC: r-bakker <ruud.bakker@oyoweb.nl>; Mention <mention@noreply.github.com>
Onderwerp: Re: [WorksOfLiam/Notepad-RPG] import (#3)

 

Hi @r-bakker <https://github.com/r-bakker>  - does the issue persist?
